project/app/urls.py
from django.urls import path
from app.views import Login, Logout, AccountRegistration, frontpage, home, post_detail, MonthCalendar, MyCalendar, MonthWithFormsCalendar,MonthWithScheduleCalendar
urlpatterns = [
    path('register/', AccountRegistration.as_view(), name='register'),
    path('login/', Login, name='login'),
    path("logout/", Logout, name="logout"),
    path("home/", home, name="home"),
    path("<slug:slug>", post_detail, name="post_detail"),
    path('mycalendar/', MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', MyCalendar.as_view(), name='mycalendar'
    ),
    path(
        'month_with_forms/',
        MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    path('month_with_forms/<int:year>/<int:month>/',MonthWithFormsCalendar.as_view(), name='month_with_forms'),
    path('bulletinboard/', frontpage, name="bulletinboard"),
    path('month/', MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', MonthCalendar.as_view(), name='month'),
    path('month_schedule/', MonthWithScheduleCalendar.as_view(), name='month_schedule'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import frontpage, frontpages

urlpatterns = [
    path('blog/', include('app.urls'), name="blog"),
    path('admin/', admin.site.urls),
    path("", frontpages.as_view(), name="frontpage"),
    path("<int:year>/<int:month>/<int:day>/", frontpages.as_view(), name="frontpage")
]

project/app/models.py
from django.db import models
from django.db import models
# ユーザー認証
from django.contrib.auth.models import User
#時間
from django.utils import timezone
import random 
import datetime

#urlの末尾を同一にしないための関数
def random_url():
     chars = '0123456789abcdefghijkmnopqrstuvwxzyABCDEFGHIJKLMNOPQRSTUVWXYZ'
     url = ''.join(random.choice(chars)for i in range(16))
     return url


#dbへデータを保存するためのクラス
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('タイトル',max_length=255)
    slug = models.SlugField(unique=True, default=random_url)
    intro = models.TextField()
    body = models.TextField('内容')
    posted_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    posted_date = models.DateTimeField(auto_now_add=True)
#調べる
class Account(models.Model):
    
    # ユーザー認証のインスタンス(1vs1関係)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # 追加フィールド
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    account_image = models.ImageField(upload_to="profile_pics",blank=True)
    def __str__(self):
        return self.user.username

class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

project/app/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Djangoブログ</title>
    <link rel="stylesheet" href="">
    </head>
    <body>
        <h1 class="titlename">ポータルサイト</h1>
        <hr>
        <a href="{% url 'frontpage' %}">ホーム</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn">ログアウト</a>
        {% else %}
        <a href="{% url 'login' %}" class="btn">ログイン</a>
        <a href="{% url 'register' %}">新規登録</a>
        {% endif %}
        <a href="{% url 'month_schedule' %}">スケジュールカレンダー</a>
        <section class="section">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </body>
</html>

project/app/templates/blog/bulletinboard.html
{% extends "blog/base.html" %}
{% block content %}
<body>
    {% if user.is_authenticated %}
    <p>{{ user.get_username }}でログイン中</p>
    {% else %}
    <p>ログインしていません</p>
    {% endif %}
{% for post in posts %}
<div class="post block">
    <h2 class="subtitle">{{post.title}}</h2>
    <small>投稿された時間：{{post.posted_date}}</small>
    <p>{{post.user}}</p>
    <p>{{post.intro}}</p>
    <a href="{% url 'post_detail' post.slug %}">もっと読む</a>
    <hr />
</div>
{% endfor %}
<h2 class="subtitle">投稿を追加</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{post_forms.as_p}}
        <div class="field">
            <div class="control">
                <button class="button is-danger">送信</button>
            </div>
        </div>
    </form>
</body>
{% endblock %}

project/app/templates/blog/calendarpage.html
{% extends "blog/base.html" %}
{% block content %}
{% for post in calendar_post %}
<p>{{post}}</p>
{% endfor %}
{% endblock %}

project/app/templates/blog/calender.html
<a href="{% url 'mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<body>
    
    <hr>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
 </body>

project/app/templates/blog/frontpage.html
{% extends "blog/base.html" %}
{% block content %}
<body>
    {% if user.is_authenticated %}
    <p>{{ user.get_username }}でログイン中</p>
    {% else %}
    <p>ログインしていません</p>
    {% endif %}
<div class="post block">
    <div class="col-md-9">
        {% include 'blog/week.html' %}
    </div>
    <div>
    <a href="{% url 'frontpage' day_previous.year day_previous.month day_previous.day %}">前の日</a>
    <p>{{ day_current | date:"Y年m月d日" }}の予定を書く</p>
    <a href="{% url 'frontpage' day_next.year day_next.month day_next.day %}">次の日</a>
    </div>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}"
                       class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                <div class="col-sm-8">
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
    </div>
</div>
<hr>
<h1>掲示板</h1>
<hr>
{% for post in posts %}
<div class="post block">
    <h2 class="subtitle">{{post.title}}</h2>
    <small>投稿された時間：{{post.posted_date}}</small>
    <p>{{post.user}}</p>
    <p>{{post.intro}}</p>
    <a href="{% url 'post_detail' post.slug %}">もっと読む</a>
    <hr />
</div>
{% endfor %}
<a href="{% url 'bulletinboard'%}">掲示板投稿はこちら！</a>
</body>
{% endblock %}

project/app/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<body>
    <p>{{UserID}}様</p>
 <p> ログアウトは
 <a href="{% url 'logout' %}">こちら</a>
 </p>
 <p>トップページは
 <a href="{% url 'frontpage' %}">こちら</a>
</p>
</body>

{% endblock %}

project/app/templates/blog/login.html
{% extends "blog/base.html" %}
{% block content %}
<body>
<h1>ログイン画面</h1>

<div class="reg">
  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}

    <table class="reg_form">
    <tr>
    <td><label for="userid">ユーザーID:</label></td>
    <td><input type="text" name="userid"></td>
    <td><label for="password">パスワード：</label></td>
    <td><input type="password" name="password"></td>
    </tr>
    </table>

    <input type="submit" class="btn" value="Login">
 </form>
</div>
   <p class="message">アカウントをお持ちですか？：
   <a href="{% url 'register' %}">アカウントを作成</a>
   </p>
</body>
{% endblock %}

project/app/templates/blog/month.html
<table class="table">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week_day_schedles in month_day_schedules %}
        <tr>
            {% for day, schedules in week_day_schedles.items %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}

            <div>
                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                {% for schedule in schedules %}
                    <p>{{ schedule.start_time }} - {{ schedule.end_time }}</p>
                    <p>{{ schedule.summary }}</p>
                    <p>{{ schedule.description | linebreaks }}</p>
                {% endfor %}
            </div>
            </td>
            {% endfor %}
        </tr>
    {% endfor %}
    <a href="{% url 'month_with_forms' %}">スケジュール投稿はこちら！</a>
    </tbody>
</table>

project/app/templates/blog/month_with_forms.html
{% extends 'blog/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

    </style>

    <a href="{% url 'month_with_forms' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'month_with_forms' month_next.year month_next.month %}">次月</a>

    <form action="" method="POST">
        {{ month_formset.management_form }}
        <table class="table">
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_forms in month_day_forms %}
                <tr>
                    {% for day, forms in week_day_forms.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}

                    <div>
                        {% if month_current.month != day.month %}
                            {{ day | date:"m/d" }}
                        {% else %}
                            {{ day.day }}
                        {% endif %}
                        {% for form in forms %}
                            {{ form.as_p }}
                        {% endfor %}
                        
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
{% endblock %}

{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

project/app/templates/blog/month_with_schedule.html
{% extends 'blog/base.html' %}
{% block content %}
<a href="{% url 'month_with_forms' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'month_with_forms' month_next.year month_next.month %}">次月</a>
        <table class="table">
            <table class="table">
                <div>{% include 'blog/month.html' %}</div>
                <thead>
                
{% endblock %}

project/app/templates/blog/mycalendar.html
{% extends 'blog/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<p>{{ user.get_username }}でログイン中</p>
{% else %}
<p>ログインなし</p>
{% endif %}
<p>トップページは
<a href="{% url 'frontpage' %}">こちら</a></p>
    <div class="row">
        <div class="col-md-3">
            {% include 'blog/calender.html' %}
            <hr>
            <div class="col-md-9">
                {% include 'blog/week.html' %}
            </div>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">送信</button>
            </form>
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

project/app/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="title">{{post.title}}</h1>
    <small>Posted at {{post.posted_date}}}</small>
    <p>{{post.user}}</p>
    <p>{{post.intro}}</p>
    <p>{{post.body}}</p>
    <hr />


    <!--　コメントされたものを表示-->
    <h2 class="subtitle">コメント</h2>

    {% for comment in post.comments.all %}
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>
                        {{comment.name}}
                        <small>{{comment.posted_date}}</small>
                    </strong>
                    <br />
                    {{comment.body}}
                </p>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="notification">
        <p>コメントはまだありません。</p>
    </div>
    <hr>
    {% endfor %}
    <!-- コメント投稿エリア　-->
    <h2 class="subtitle">コメントを追加</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="field">
            <div class="control">
                <button class="button is-danger">送信</button>
            </div>
        </div>
    </form>
{% endblock %}

project/app/templates/blog/register.html
{% extends "blog/base.html" %}
{% block content %}

<body>
<h1>新規登録</h1>

 {% if AccountCreate %}
   <h1>登録完了!</h1>

 {% else %}
   <div class="reg">
   <table class="reg_form">

   <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   {{ account_form.as_table }}
   {{ add_account_form.as_table }}
   <tr><td></td><td>
   <input class="btn" type="submit" name="" value="登録">
   </td></tr>
   </form>

   </table>
   </div>
 {% endif %}
{% endblock %}

project/app/templates/blog/week.html
 <table class="table table-bordered">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    <tr>
        {% for day, schedules in week_day_schedules.items %}
            <td>
                <!-- 日付 -->
                {% if week_first.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}
                <br>

                <!-- その日のスケジュール -->
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>